# Generated by Django 5.0 on 2024-03-06 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0013_jobapplymodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='job_model',
            name='category',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='job_model',
            name='openings',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='job_model',
            name='skill',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
